#!/usr/bin/env python3
"""Compatibility facade for the modular index valuation implementation."""

from index_valuation.cache import (
    _anchor_months,
    _date_chunks,
    all_source_ids,
    cache_fingerprint,
    conditional_headers,
    fetch_ndxtmc_source,
    format_nasdaq_url,
    load_catalog,
    load_manifest,
    load_source_caches,
    source_cache_id,
    source_fingerprint,
    validate_source_data,
)
from index_valuation.cli import build_performance_metrics, main, parse_args
from index_valuation.common import (
    BASE_HEADERS,
    CACHE_SCHEMA_VERSION,
    DEFAULT_CACHE_DIR,
    DEFAULT_CATALOG,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_PAGE_SCRIPT,
    DEFAULT_PUBLISH_DIR,
    DIRECT_ASSET_IDS,
    DQYDJ_HEADERS,
    DQYDJ_SOURCE_ID,
    EXPECTED_ASSET_IDS,
    FetchResponse,
    FULL_SCAN_BUFFER_MONTHS,
    GOLD_ASSET_ID,
    GOLD_HEADERS,
    GOLD_SOURCE_ID,
    HttpClient,
    NASDAQ_HEADERS,
    NASDAQ_TICKERS,
    NDXTMC_HISTORY_CHUNK_DAYS,
    NDXTMC_HISTORY_HEADERS,
    NDXTMC_LIVE_START,
    NDXTMC_SOURCE_ID,
    NDXTMC_WORKBOOK_HEADERS,
    PERFORMANCE_TARGETS,
    PROXY_ASSET_IDS,
    RELATIVE_PROXY_ASSET_ID,
    SCHEMA_VERSION,
    SHANGHAI_TZ,
    SNOWBALL_HEADERS,
    SNOWBALL_SOURCE_ID,
    SOURCE_RATING_LABELS,
    TAIL_DAYS,
    TableParser,
    ValuationError,
    WINDOW_MONTHS,
    add_months,
    atomic_write_json,
    atomic_write_text,
    current_shanghai_time,
    finite_number,
    last_complete_month,
    month_start,
    positive_number,
    years_ago,
)
from index_valuation.models import (
    _asset_status,
    _parse_response,
    _source_name,
    _source_page_url,
    _unavailable_asset,
    aggregate_status,
    build_direct_asset,
    build_gold_asset,
    build_proxy_asset,
    build_relative_proxy_asset,
    iso_age_hours,
    percentile_midrank,
    quantile,
    run_parallel_requests,
    select_contiguous_window,
)
from index_valuation.pipeline import _summary_values, build_payload
from index_valuation.renderer import render_html
from index_valuation.sources import (
    _match_text,
    _store_price_point,
    _xlsx_shared_strings,
    merge_ndxtmc_points,
    merge_price_points,
    monthly_average,
    ndxtmc_workbook_matches_cache,
    parse_dqydj_pe,
    parse_gold_snapshot,
    parse_nasdaq_history,
    parse_ndxtmc_history,
    parse_ndxtmc_workbook,
    parse_normalized_ndxtmc,
    parse_snowball_snapshot,
    validate_ndxtmc_boundary,
    validate_pe_points,
    validate_price_points,
)

__all__ = [
    "BASE_HEADERS", "CACHE_SCHEMA_VERSION", "DEFAULT_CACHE_DIR", "DEFAULT_CATALOG",
    "DEFAULT_OUTPUT_DIR", "DEFAULT_PAGE_SCRIPT", "DEFAULT_PUBLISH_DIR",
    "DIRECT_ASSET_IDS", "DQYDJ_HEADERS", "DQYDJ_SOURCE_ID", "EXPECTED_ASSET_IDS",
    "FULL_SCAN_BUFFER_MONTHS", "FetchResponse", "GOLD_ASSET_ID", "GOLD_HEADERS",
    "GOLD_SOURCE_ID", "HttpClient", "NASDAQ_HEADERS", "NASDAQ_TICKERS",
    "NDXTMC_HISTORY_CHUNK_DAYS", "NDXTMC_HISTORY_HEADERS", "NDXTMC_LIVE_START",
    "NDXTMC_SOURCE_ID", "NDXTMC_WORKBOOK_HEADERS", "PERFORMANCE_TARGETS",
    "PROXY_ASSET_IDS", "RELATIVE_PROXY_ASSET_ID", "SCHEMA_VERSION", "SHANGHAI_TZ",
    "SNOWBALL_HEADERS", "SNOWBALL_SOURCE_ID", "SOURCE_RATING_LABELS", "TAIL_DAYS",
    "TableParser", "ValuationError", "WINDOW_MONTHS", "add_months", "aggregate_status",
    "all_source_ids", "atomic_write_json", "atomic_write_text", "build_direct_asset",
    "build_gold_asset", "build_payload", "build_performance_metrics", "build_proxy_asset",
    "build_relative_proxy_asset", "cache_fingerprint", "conditional_headers",
    "current_shanghai_time", "fetch_ndxtmc_source", "finite_number",
    "format_nasdaq_url", "iso_age_hours", "last_complete_month", "load_catalog",
    "load_manifest", "load_source_caches", "main", "merge_ndxtmc_points",
    "merge_price_points", "month_start", "monthly_average",
    "ndxtmc_workbook_matches_cache", "parse_args", "parse_dqydj_pe",
    "parse_gold_snapshot", "parse_nasdaq_history", "parse_ndxtmc_history",
    "parse_ndxtmc_workbook", "parse_normalized_ndxtmc", "parse_snowball_snapshot",
    "percentile_midrank", "positive_number", "quantile", "render_html",
    "run_parallel_requests", "select_contiguous_window", "source_cache_id",
    "source_fingerprint", "validate_ndxtmc_boundary", "validate_pe_points",
    "validate_price_points", "validate_source_data", "years_ago",
]


if __name__ == "__main__":
    raise SystemExit(main())
